version: 2
jobs:
  unittest:
    docker:
      - image: circleci/rust:1.42.0
    steps:
      - checkout
      - run: cargo test --all
  build:
    docker:
      - image: circleci/rust:1.42.0
    steps:
      - checkout
      - run: cargo build
workflows:
  version: 2
  build_and_test:
    jobs:
      - unittest
